Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/07/2017
Var
   Nota:Inteiro


Inicio
       leia(Nota)
       se(nota>=10) entao
          Escreva("Positiva")
       senao
          Escreva("Negativa")
       fimse


Fimalgoritmo